---
title: "Age-Structured SIR with Arrays"
subtitle: "odin2/dust2 Vignette 04 (R)"
format:
  html:
    toc: true
    code-fold: false
---

## Introduction

Age-structured SIR model using arrays in odin2.

## Model Definition

```{r}
library(odin2)
library(dust2)

sir_age <- odin({
  n_age <- parameter(3)
  dim(S) <- n_age
  dim(I) <- n_age
  dim(R) <- n_age
  dim(beta) <- n_age
  dim(S0) <- n_age
  dim(I0) <- n_age

  deriv(S[]) <- -beta[i] * S[i] * total_I / N
  deriv(I[]) <- beta[i] * S[i] * total_I / N - gamma * I[i]
  deriv(R[]) <- gamma * I[i]

  total_I <- sum(I)

  initial(S[]) <- S0[i]
  initial(I[]) <- I0[i]
  initial(R[]) <- 0

  S0[] <- parameter()
  I0[] <- parameter()
  beta[] <- parameter()
  gamma <- parameter(0.1)
  N <- parameter(1000)
})
```

## Parameters and Simulation

```{r}
pars <- list(
  n_age = 3,
  S0 = c(300, 500, 190),
  I0 = c(5, 3, 2),
  beta = c(0.4, 0.3, 0.2),
  gamma = 0.1,
  N = 1000
)

sys <- dust_system_create(sir_age, pars, ode_control = dust_ode_control())
dust_system_set_state_initial(sys)
times <- seq(0, 200, by = 0.5)
result <- dust_system_simulate(sys, times)
cat("State dimensions:", dim(result), "\n")
```

## Visualising by Age Group

```{r}
age_labels <- c("Children (0-14)", "Adults (15-64)", "Elderly (65+)")
cols <- c("blue", "red", "green")

# Infected by age group
plot(NULL, xlim = range(times), ylim = c(0, max(result[4:6, ])),
     xlab = "Time", ylab = "Infected", main = "Infected by Age Group")
for (i in 1:3) {
  lines(times, result[3 + i, ], col = cols[i], lwd = 2)
}
legend("topright", legend = age_labels, col = cols, lwd = 2)
```

```{r}
par(mfrow = c(1, 3), mar = c(4, 4, 2, 1))
for (g in 1:3) {
  plot(times, result[g, ], type = "l", col = "blue", lwd = 2,
       xlab = "Time", ylab = "Population", main = age_labels[g],
       ylim = c(0, max(result[g, ])))
  lines(times, result[3 + g, ], col = "red", lwd = 2)
  lines(times, result[6 + g, ], col = "green", lwd = 2)
}
```

## Final Attack Rates

```{r}
for (g in 1:3) {
  R_final <- result[6 + g, length(times)]
  N_group <- pars$S0[g] + pars$I0[g]
  ar <- 100 * R_final / N_group
  cat(age_labels[g], ": Attack rate =", round(ar, 1), "%\n")
}
```
